### PR TITLE
Show helpful error message when vikit api key is not provided

### PR DESCRIPTION
**Pull request by prithiv256**

### CODE REVIEW

**Review by jeffmac-aix — APPROVED** [review]
lgtm

**Comment by prithiv256** [comment]
Does the build server specify env variables differently? I can't reproduce the error locally

**Comment by jeffmac-aix** [comment]
the build server use github actions env variables. In our case the expected variable is set to 3, so I am don't understand yet why we have this error.
image

**Comment by jeffmac-aix** [comment]
Hi Prithiv, I hope this message finds you well. I've noticed that your Pull Request (PR) could benefit from some updates to align with the latest changes in the main branch, and it is likely to resolve the build not passing.

To update your PR, you can follow these steps:

Switch to your feature branch:

git checkout key-missing-error
Update your feature branch key-missing-error with the latest changes from the main branch:

git fetch upstream
git merge upstream/main
Resolve any merge conflicts, if necessary, by manually editing the affected files.
Push the merged changes to your fork:

git push origin key-missing-error
Verify that your PR reflects the latest changes from the main branch and that your feature branch is up to date.

If you encounter any difficulties or have any questions, please don't hesitate to reach out. I'm here to help.

Thank you for your contribution to the project.

Best regards,
JF

**Comment by jeffmac-aix** [comment]
PR integrated in another urgent one https://github.com/Vikit-ai/sdk/pull/108

**Pull request closed without merging**
